### ISSUE TITLE
SearchBox skipping some keys when text is typed fast

### ISSUE THREAD

**Issue by leonardobaggio** [algolia/react-instantsearch#150]
Hi folks!

I've followed the instructions at Algolia Community and have set up a demo using the sample code (and the "bestbuy" sample index).

As soon as I typed the first few words I've immediatally noticed a huge lag in the textbox, like in the gif below.

**Me, trying to type "The quick brown fox jumps over the lazy doggo"**
![image](http://i.imgur.com/eFAoAvD.gif)

I've take a look at the console, but the only thing that came up was this weird verbose about setTimout functions

![image](https://user-images.githubusercontent.com/18285859/27927467-3bec0d72-6262-11e7-90b8-f56e515de449.png)

Also, i've checked at Chrome Developer Tools' Performance tab an noticed that are several chained events occouring while typing.

![image](https://user-images.githubusercontent.com/18285859/27927718-0cffd240-6263-11e7-94cb-a9a1ea94f52d.png)

Due to the intermittently behaviour of the "key skipping" issue and several verbose logs that have been shown at console, my first suspiction is that this setTimeout  calls could be related, but I have not gone so far enough to any conclusion.

Does anyone here have experienced this, or have a little more experience to tell if there is something wrong by looking at Performance log?

I don't know exactly but, Im using some other 3rd party libraries, such as Sentry (Raven.js) and Heap Analytics. Maybe they could possibly affect and cause this:

Any help is appreciated 👍 :)

Thanks,
Leo

**Comment by mthuret** [comment]
Hi @leonardobaggio, 

Could you try two things: 

1. Use the library without raven and see if you still have those warnings?

2. Use the version 4.0.4 of react-instantsearch with your actual code and tell us if you still have a lag?

**Comment by leonardobaggio** [comment]
Hi @mthuret ! Thank you for your reply.

Coincidentally, I've tested the library without raven and heap sometime earlier before I checked your comment here, but this issue remained (I didn't analysed the logs since nothing had changed).

However, I've mistakenly included the component in a production build today and, for a unknown reason, everthing seems to works just fine, except by the fact the CSS file have not loaded properly from the CDN.

The next step I'm planning to take now is to fix this CSS issue and see if this error keeps solved at production or returns, thus enabling us to tie it to the fact that all the components are just plain style-less html, and somehow reduced the lag.

**Comment by leonardobaggio** [comment]
I've checked and noticed that this may occur even without the CSS.

Also, I can reproduce the same issue in Algolia InstantSearch Material Example (https://community.algolia.com/react-instantsearch/examples/material-ui/)

**The quick brown fox...**
![9xvkqpezs5](https://user-images.githubusercontent.com/18285859/28023597-b8e9b9b4-6564-11e7-97e5-7f9faca87996.gif)

Ok.. my workstation is runing some CPU intensive tasks, and isn't hard to see > 70% CPU usages along the day, I can also notice some kind of lag while typing in other places... but only in Instantsearch's SearchBox I got keys being skipped.

Maybe the events being used to capture the keys, or something related with the search throttling are resulting in this.

**Comment by mthuret** [comment]
I reproduce it by stressing a bit my mac, that's clearly a bug, and it was introduce with this commit => https://github.com/algolia/react-instantsearch/commit/0945958111c9c428b37a94d67bc535a11a15b361

So, if you run 4.0.4 you shouldn't experience the same thing. Maybe you can confirm? 

I'll investigate to see if some code can be change to keep the fix or if we'll need to rollback.

Thanks!

**Comment by leonardobaggio** [comment]
Confirmed @mthuret! thank you!

![dfinddic0q](https://user-images.githubusercontent.com/18285859/28038288-c4c00a2e-6594-11e7-948d-b4c88137d4db.gif)

The searchbox stills have a laggish feeling but it does not skips the keys anymore.

**Comment by denkristoffer** [comment]
Seeing the same behaviour with 4.0.7, some characters are skipped.

**Comment by mthuret** [comment]
I released a 4.0.8 and 4.1.0-beta.1 that fix this.

**Comment by denkristoffer** [comment]
Hmm, this is still happening for me with 4.0.8 although the issue in #150 seems to be fixed.

**Comment by mthuret** [comment]
@denkristoffer what is still happening? #150 is this issue.
