### ISSUE TITLE
Got undefined is not an object evaluating window.navigator.userAgent.includes when running on iOS 12.0

### ISSUE THREAD

**Issue by bernhardoj** [algolia/react-instantsearch#3188]
## 🐛 Bug description

I am using react-instantsearch-native v6.6.0. It is all working when I run it on iOS 14 and higher. Then, I try to use it on iOS 12.0, and then I got this error `TypeError: undefined is not an object evaluating window.navigator.userAgent.includes` from `InstantSearch` component.

I have tried to upgrade the library to the latest version (v6.15.0) but had no success.

Thank you!

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Use InstantSearch component
2. Run it on iOS 12.0
3. See error

**Live reproduction:**

This is the code I used:
```
import algoliasearch from 'algoliasearch'
import { InstantSearch } from 'react-instantsearch-native'

const searchClient = algoliasearch(apiIndexAlgolia, apiKeyAlgolia)
<InstantSearch searchClient={searchClient />
```

## 💭 Expected behavior

The InstantSearch working as expected, no throwing any error.

## 🖥 Screenshots

![Capture](https://user-images.githubusercontent.com/50919443/139803723-9a92555d-3cc9-414a-b72a-bddb68fbbe0c.PNG)

## Environment

- OS: iOS
- Version: 12.0

**Comment by francoischalifour** [comment]
This should be fixed in v16.15.0 via #3184. Can you make sure that the React InstantSearch dependency is effectively upgraded to this version?

**Comment by bernhardoj** [comment]
How do I specifically check React InstantSearch version? I found in node_modules react-instantsearch-core and react-instantsearch-native. Both modules are v6.15.0 (from package.json).

react-instantsearch-core package.json:
```
"name": "react-instantsearch-core",
"version": "6.15.0",
"description": "⚡ Lightning-fast search for React, by Algolia",
"main": "dist/cjs/index.js",
"module": "dist/es/index.js",
....
```

react-instantsearch-native package.json:
```
"name": "react-instantsearch-native",
"version": "6.15.0",
"description": "⚡ Lightning-fast search for React Native, by Algolia",
"main": "dist/cjs/index.js",
"module": "dist/es/index.js",
....
```

From the PR you give, it seems the bug is fixed on isMetadataEnabled()
But, I checked on 
react-instantsearch-core -> dist -> umd -> ReactInstantSearchCore.js

the isMetadataEnabled() is different (still not updated):
```
function isMetadataEnabled() {
    return (typeof window === "undefined" ? "undefined" : _typeof$1(window)) === 'object' && _typeof$1(window.navigator) === 'object' && typeof window.navigator.userAgent === 'string' && window.navigator.userAgent.includes('Algolia Crawler') && _typeof$1(window.document) === 'object';
}
```

**Comment by bernhardoj** [comment]
I have also tried to create a new clean project and run npm i react-instantsearch-native but the code still the same as above.

**Comment by Haroenv** [comment]
@bernhardoj, can you make a GitHub repository that shows how this shows as an issue? The condition that you mentioned is the correct one, as it checks all members before calling .includes. Are you using regular react native?

**Comment by bernhardoj** [comment]
It's a company app so I can't share the repository.
Yeah my bad, the condition is updated already. 
Yes, I use React Native. May I know, what do you mean by regular React Native?

**Comment by Haroenv** [comment]
If anything is special around the setup. I've tried the published version in our example just now and the error doesn't happen, so I don't understand how you would still get the error. I think somehow an older version ended up in your dependency tree.

**Comment by bernhardoj** [comment]
After reading your comment, I tried to clear the node_modules, package-lock.json, pods, podfile.lock, and reinstall it. I also did Clean Build Folder and then restarted my Mac.

Then I tried to run again the app and it's working as expected now.

Thank you so much for all the helps! ^^

**Comment by Haroenv** [comment]
Glad your issue is solved! it must have been some kind of cache in the end I assume. Have a great time building @bernhardoj !
