### ISSUE TITLE
Two identical requests when using connectStateResults

### ISSUE THREAD

**Issue by dannylin108** [algolia/react-instantsearch#3225]
## 🐛 Bug description

When wrapping `<Hits/>` with a component created with `connectStateResults` and passing `searchAsYouType={false}` for `<SearchBox>` , after typing in a query and hitting <enter>, each time it sends two identical requests to Algolia.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Do mentioned modifications of Algolia demo-app
2. Open the app to start searching
3. Open Network tab of Devtools
4. Enter any query, hit 'enter'
5. Network tab shows two identical requests per query are sent to the server

**Live reproduction:**

This is the forked sandbox of Algolia demo-app with all needed modifications to illustrate the issue 

https://codesandbox.io/s/vigorous-sara-799j2

## 💭 Expected behavior

One request per query is sent to Algolia

## 🖥 Screenshots

![doubled request](https://user-images.githubusercontent.com/72641467/144968704-4bcc6e75-35cd-4000-ad7a-dd1226bdb2e1.png)

## Environment

- OS: Linux
- Browser: Chrome, Firefox

**Comment by Haroenv** [comment]
This is solved by the latest version of algoliasearch, which caches in-flight network requests: https://codesandbox.io/s/nervous-wu-0p7s3

**Comment by dannylin108** [comment]
This sandbox is not using latest one? 

Still the same

![dublicated requests](https://user-images.githubusercontent.com/72641467/145146978-90c85f99-4870-4afd-896f-0a0ef2e6b7b3.png)

**Comment by Haroenv** [comment]
These two queries actually aren't identical, the second query has "page: 0", and that's why the cache isn't hit. If you render a fallback that renders virtual hits and pagination in the no results case, that prevents those queries being sent: https://codesandbox.io/s/keen-gagarin-32s4p?file=/src/App.js

```js
const VirtualHits = connectHits(() => null);
const VirtualPagination = connectPagination(() => null);

const Results = connectStateResults(({ searchState, children, fallback }) => {
  if (!searchState || !searchState.query) return fallback;

  return children;
});

// ...
<Results
  fallback={
    <>
      <VirtualHits />
      <VirtualPagination />
    </>
  }
>
  <Hits hitComponent={Hit} />
  <div className="pagination">
    <Pagination />
  </div>
</Results>
```

**Comment by dannylin108** [comment]
Oh, yeah! That's what I was looking for. Thanks a lot!
